### ISSUE TITLE
Question about Readme instructions

### ISSUE THREAD

**Issue by flizzer** [AI-Maker-Space/Interactive-Dev-Environment-for-LLM-Development#1]
Greetings and thanks for the tutorial provided here!  I'm doing the setup on a Windows machine.  As I'm going thru it, I have a question regarding the use of WSL2 and VS Code.  It looks like per the below table, conda and git are to be installed within WSL2, but I'm assuming VS Code is to be installed within Windows (outside of WSL2) itself.  Is that correct?  My Windows machine already has VS Code and Git setup so I'm just trying to understand what should be installed within WSL2 vs. Windows.

![image](https://github.com/AI-Maker-Space/Interactive-Dev-Environment-for-LLM-Development/assets/596833/739e2d6c-89be-4216-8311-799507b8d23d)

Thanks in advance for any clarfication.

Brian

**Comment by chris-alexiuk** [comment]
Yes, you are correct! 

I'll clarify the instructions.
